version: '3.8'

services:
  mongo:
    image: mongo:5
    container_name: ns_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ns_case
    volumes:
      - mongo_data:/data/db
    networks:
      - ns_network

  redis:
    image: redis:7-alpine
    container_name: ns_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ns_network

  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile.api
    container_name: ns_api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ns_case
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=devsecret
      - NODE_ENV=development
    depends_on:
      - mongo
      - redis
    networks:
      - ns_network
    volumes:
      - ../apps/api:/app/apps/api
      - ../packages:/app/packages

  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile.web
    container_name: ns_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NODE_ENV=development
    depends_on:
      - api
    networks:
      - ns_network
    volumes:
      - ../apps/web:/app/apps/web
      - ../packages:/app/packages

networks:
  ns_network:
    driver: bridge

volumes:
  mongo_data: